insert into change_headers (id, ts) values (65, '2026-10-10') on duplicate key update ts = values(ts);

insert into change_descriptions (id, lang, description) values (65, 'ru', 'Калькуляторы получили короткие адреса: например, proxyforgame.com/ru/costs вместо proxyforgame.com/ru/ogame/calc/costs.php. Старые ссылки и закладки продолжают работать и сами ведут на новые адреса.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (65, 'en', 'The calculators now have short addresses: for example, proxyforgame.com/en/costs instead of proxyforgame.com/en/ogame/calc/costs.php. Old links and bookmarks keep working and take you to the new addresses automatically.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (65, 'pt', 'As calculadoras ganharam endereços curtos: por exemplo, proxyforgame.com/pt/costs em vez de proxyforgame.com/pt/ogame/calc/costs.php. Os links e favoritos antigos continuam a funcionar e levam automaticamente aos novos endereços.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (65, 'de', 'Die Rechner haben jetzt kurze Adressen: zum Beispiel proxyforgame.com/de/costs statt proxyforgame.com/de/ogame/calc/costs.php. Alte Links und Lesezeichen funktionieren weiterhin und führen automatisch zu den neuen Adressen.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (65, 'pl', 'Kalkulatory mają teraz krótkie adresy: na przykład proxyforgame.com/pl/costs zamiast proxyforgame.com/pl/ogame/calc/costs.php. Stare linki i zakładki nadal działają i same prowadzą pod nowe adresy.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (65, 'es', 'Las calculadoras tienen ahora direcciones cortas: por ejemplo, proxyforgame.com/es/costs en lugar de proxyforgame.com/es/ogame/calc/costs.php. Los enlaces y marcadores antiguos siguen funcionando y llevan automáticamente a las nuevas direcciones.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (65, 'fr', 'Les calculateurs ont désormais des adresses courtes : par exemple, proxyforgame.com/fr/costs au lieu de proxyforgame.com/fr/ogame/calc/costs.php. Les anciens liens et favoris fonctionnent toujours et mènent automatiquement aux nouvelles adresses.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (65, 'it', 'I calcolatori ora hanno indirizzi brevi: ad esempio, proxyforgame.com/it/costs invece di proxyforgame.com/it/ogame/calc/costs.php. I vecchi link e segnalibri continuano a funzionare e portano automaticamente ai nuovi indirizzi.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (65, 'nl', 'De calculators hebben nu korte adressen: bijvoorbeeld proxyforgame.com/nl/costs in plaats van proxyforgame.com/nl/ogame/calc/costs.php. Oude links en bladwijzers blijven werken en leiden automatisch naar de nieuwe adressen.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (65, 'sk', 'Kalkulačky majú teraz krátke adresy: napríklad proxyforgame.com/sk/costs namiesto proxyforgame.com/sk/ogame/calc/costs.php. Staré odkazy a záložky naďalej fungujú a samy vedú na nové adresy.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (65, 'tr', 'Hesaplayıcılar artık kısa adreslere sahip: örneğin proxyforgame.com/tr/ogame/calc/costs.php yerine proxyforgame.com/tr/costs. Eski bağlantılar ve yer imleri çalışmaya devam ediyor ve sizi otomatik olarak yeni adreslere yönlendiriyor.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (65, 'bs', 'Kalkulatori sada imaju kratke adrese: na primjer, proxyforgame.com/bs/costs umjesto proxyforgame.com/bs/ogame/calc/costs.php. Stari linkovi i oznake i dalje rade i automatski vode na nove adrese.') on duplicate key update description = values(description);
