insert into change_headers (id, ts) values (64, '2026-10-04') on duplicate key update ts = values(ts);

insert into change_descriptions (id, lang, description) values (64, 'ru', 'Калькулятор стоимости: на вкладке «Общие» теперь можно выбрать страну и вселенную — скорость экономики и скорость исследований подставятся автоматически.<br>Калькуляторы стоимости и производства: бонус класса теперь вводится как значение «Всего» из таблицы OGame, поле уровня формы жизни убрано — раньше бонус учитывался дважды.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (64, 'en', 'Costs calculator: on the "Common" tab you can now pick a country and a universe, and the economy speed and research speed are filled in automatically.<br>Costs and production calculators: the class bonus is now entered as the "Total" value from the OGame table, and the life form level field is gone - the bonus used to be counted twice.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (64, 'pt', 'Calculadora de Custos: no separador "Geral" agora pode escolher o país e o universo, e a velocidade económica e a velocidade de pesquisa são preenchidas automaticamente.<br>Calculadoras de Custos e de Produção: o bónus de classe é agora introduzido como o valor "Total" da tabela do OGame, e o campo do nível da forma de vida foi removido - antes o bónus era contado duas vezes.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (64, 'de', 'Kostenberechnung: Im Reiter "Allgemein" kannst du jetzt Land und Universum auswählen, Wirtschaftstempo und Forschungsgeschwindigkeit werden automatisch eingetragen.<br>Kosten- und Produktionsberechnung: Der Klassenbonus wird jetzt als Wert "Gesamt" aus der OGame-Tabelle eingegeben, das Feld für die Lebensform-Stufe entfällt - bisher wurde der Bonus doppelt gezählt.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (64, 'pl', 'Kalkulator kosztów: na karcie "Ogólne" można teraz wybrać kraj i uniwersum, a prędkość ekonomiczna i prędkość badawcza zostaną uzupełnione automatycznie.<br>Kalkulatory kosztów i produkcji: premię klasy wpisuje się teraz jako wartość "Łącznie" z tabeli OGame, a pole poziomu formy życia zostało usunięte - wcześniej premia była liczona podwójnie.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (64, 'es', 'Calculadora de Costes: en la pestaña "General" ahora puedes elegir el país y el universo, y la velocidad económica y la velocidad de investigación se rellenan automáticamente.<br>Calculadoras de Costes y de Producción: la bonificación de clase se introduce ahora como el valor "Total" de la tabla de OGame, y se ha eliminado el campo del nivel de forma de vida - antes la bonificación se contaba dos veces.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (64, 'fr', 'Calculateur de coûts : dans l''onglet « Général », tu peux désormais choisir le pays et l''univers, et la vitesse économique et la vitesse de recherche sont remplies automatiquement.<br>Calculateurs de coûts et de production : le bonus de classe se saisit désormais comme la valeur « Total » du tableau OGame, et le champ du niveau de forme de vie a disparu - le bonus était auparavant compté deux fois.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (64, 'it', 'Calcolatore di Costi: nella scheda "Generale" ora puoi scegliere il paese e l''universo, e la velocità economia e la velocità di ricerca vengono compilate automaticamente.<br>Calcolatori di Costi e di Produzione: il bonus di classe si inserisce ora come valore "Totale" dalla tabella di OGame, e il campo del livello della forma di vita è stato rimosso - prima il bonus veniva contato due volte.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (64, 'nl', 'Kostenberekening: op het tabblad "Algemeen" kun je nu een land en een universum kiezen, en de economische snelheid en de onderzoekssnelheid worden automatisch ingevuld.<br>Kosten- en productieberekening: de klassebonus wordt nu ingevoerd als de waarde "Totaal" uit de OGame-tabel, en het veld voor het Life Form-niveau is verdwenen - voorheen werd de bonus dubbel geteld.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (64, 'sk', 'Kalkulátor cien: na karte "Všeobecné" teraz môžete vybrať krajinu a vesmír a rýchlosť ekonomiky aj rýchlosť výskumu sa vyplnia automaticky.<br>Kalkulátory cien a produkcie: bonus triedy sa teraz zadáva ako hodnota "Spolu" z tabuľky OGame a pole úrovne formy života bolo odstránené - predtým sa bonus započítaval dvakrát.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (64, 'tr', 'Maliyet Hesaplayıcı: "Genel" sekmesinde artık ülke ve evren seçebilirsiniz; ekonomi hızı ve araştırma hızı otomatik olarak doldurulur.<br>Maliyet ve Üretim Hesaplayıcıları: sınıf bonusu artık OGame tablosundaki "Toplam" değeri olarak girilir ve yaşam formu seviyesi alanı kaldırıldı - bonus önceden iki kez hesaba katılıyordu.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (64, 'bs', 'Kalkulator troškova: na kartici "Opšte" sada možete odabrati zemlju i univerzum, a ekonomska brzina i brzina istraživanja popunjavaju se automatski.<br>Kalkulatori troškova i produkcije: bonus klase sada se unosi kao vrijednost "Ukupno" iz OGame tabele, a polje nivoa oblika života je uklonjeno - ranije se bonus računao dvaput.') on duplicate key update description = values(description);
