insert into change_headers (id, ts) values (62, '2026-08-30') on duplicate key update ts = values(ts);

insert into change_descriptions (id, lang, description) values (62, 'ru', 'Калькулятор производства: бонус Гусеничников к добыче теперь ограничен 50 % производства шахты, как в игре.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (62, 'en', 'Production calculator: the Crawler bonus to production is now capped at 50% of mine output, as in the game.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (62, 'pt', 'Calculadora de produção: o bônus dos Crawlers à produção agora é limitado a 50% da produção da mina, como no jogo.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (62, 'de', 'Produktionsrechner: Der Crawler-Bonus auf die Förderung ist jetzt wie im Spiel auf 50 % der Minenproduktion begrenzt.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (62, 'pl', 'Kalkulator produkcji: premia Pełzaczy do wydobycia jest teraz ograniczona do 50% produkcji kopalni, tak jak w grze.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (62, 'es', 'Calculadora de producción: la bonificación de los Taladradores a la producción ahora está limitada al 50 % de la producción de la mina, como en el juego.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (62, 'fr', 'Calculateur de production : le bonus des Foreuses à la production est désormais plafonné à 50 % de la production de la mine, comme dans le jeu.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (62, 'it', 'Calcolatore di produzione: il bonus dei Crawler alla produzione è ora limitato al 50% della produzione della miniera, come nel gioco.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (62, 'nl', 'Productiecalculator: de Crawler-bonus op de productie is nu begrensd op 50% van de mijnproductie, net als in het spel.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (62, 'sk', 'Kalkulátor produkcie: bonus Crawlerov k ťažbe je teraz obmedzený na 50 % produkcie bane, tak ako v hre.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (62, 'tr', 'Üretim hesaplayıcı: Paletlilerin üretime kattığı bonus artık oyundaki gibi maden üretiminin %50''si ile sınırlı.') on duplicate key update description = values(description);
insert into change_descriptions (id, lang, description) values (62, 'bs', 'Kalkulator proizvodnje: bonus Puzavaca na proizvodnju sada je ograničen na 50% proizvodnje rudnika, kao u igri.') on duplicate key update description = values(description);
