SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `proxyforgame`
--

-- --------------------------------------------------------

--
-- Table structure for table `change_descriptions`
--

DROP TABLE IF EXISTS `change_descriptions`;
CREATE TABLE IF NOT EXISTS `change_descriptions` (
  `id` smallint(6) NOT NULL,
  `lang` varchar(2) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`,`lang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `change_headers`
--

DROP TABLE IF EXISTS `change_headers`;
CREATE TABLE IF NOT EXISTS `change_headers` (
  `id` smallint(6) NOT NULL,
  `ts` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `countries`
--

DROP TABLE IF EXISTS `countries`;
CREATE TABLE IF NOT EXISTS `countries` (
  `lang` varchar(2) NOT NULL,
  `lang2` varchar(2) NOT NULL,
  `name` varchar(70) NOT NULL,
  PRIMARY KEY (`lang`,`lang2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Data for table `countries`
--

INSERT INTO `countries` (`lang`, `lang2`, `name`) VALUES
('ar', 'ar', 'Argentina'),
('ar', 'br', 'Brasil'),
('ar', 'cz', 'Česká Republika'),
('ar', 'de', 'Deutschland'),
('ar', 'dk', 'Danmark'),
('ar', 'en', 'United Kingdom'),
('ar', 'es', 'España'),
('ar', 'fi', 'Suomi'),
('ar', 'fr', 'France'),
('ar', 'gr', 'Ελλάδα'),
('ar', 'hr', 'Hrvatska'),
('ar', 'hu', 'Magyarország'),
('ar', 'it', 'Italia'),
('ar', 'jp', '日本'),
('ar', 'mx', 'México'),
('ar', 'nl', 'Nederland'),
('ar', 'no', 'Norge'),
('ar', 'pl', 'Polska'),
('ar', 'pt', 'Portugal'),
('ar', 'ro', 'Romania'),
('ar', 'ru', 'Российская Федерация'),
('ar', 'se', 'Sverige'),
('ar', 'si', 'Slovenija'),
('ar', 'sk', 'Slovensko'),
('ar', 'tr', 'Türkiye'),
('ar', 'tw', '台灣'),
('ar', 'us', 'USA'),
('br', 'ar', 'Argentina'),
('br', 'br', 'Brasil'),
('br', 'cz', 'Česká Republika'),
('br', 'de', 'Deutschland'),
('br', 'dk', 'Danmark'),
('br', 'en', 'United Kingdom'),
('br', 'es', 'España'),
('br', 'fi', 'Suomi'),
('br', 'fr', 'France'),
('br', 'gr', 'Ελλάδα'),
('br', 'hr', 'Hrvatska'),
('br', 'hu', 'Magyarország'),
('br', 'it', 'Italia'),
('br', 'jp', '日本'),
('br', 'mx', 'México'),
('br', 'nl', 'Nederland'),
('br', 'no', 'Norge'),
('br', 'pl', 'Polska'),
('br', 'pt', 'Portugal'),
('br', 'ro', 'Romania'),
('br', 'ru', 'Российская Федерация'),
('br', 'se', 'Sverige'),
('br', 'si', 'Slovenija'),
('br', 'sk', 'Slovensko'),
('br', 'tr', 'Türkiye'),
('br', 'tw', '台灣'),
('br', 'us', 'USA'),
('cz', 'ar', 'Argentina'),
('cz', 'br', 'Brasil'),
('cz', 'cz', 'Česká Republika'),
('cz', 'de', 'Deutschland'),
('cz', 'dk', 'Danmark'),
('cz', 'en', 'United Kingdom'),
('cz', 'es', 'España'),
('cz', 'fi', 'Suomi'),
('cz', 'fr', 'France'),
('cz', 'gr', 'Ελλάδα'),
('cz', 'hr', 'Hrvatska'),
('cz', 'hu', 'Magyarország'),
('cz', 'it', 'Italia'),
('cz', 'jp', '日本'),
('cz', 'mx', 'México'),
('cz', 'nl', 'Nederland'),
('cz', 'no', 'Norge'),
('cz', 'pl', 'Polska'),
('cz', 'pt', 'Portugal'),
('cz', 'ro', 'Romania'),
('cz', 'ru', 'Российская Федерация'),
('cz', 'se', 'Sverige'),
('cz', 'si', 'Slovenija'),
('cz', 'sk', 'Slovensko'),
('cz', 'tr', 'Türkiye'),
('cz', 'tw', '台灣'),
('cz', 'us', 'USA'),
('de', 'ar', 'Argentina'),
('de', 'br', 'Brasil'),
('de', 'cz', 'Česká Republika'),
('de', 'de', 'Deutschland'),
('de', 'dk', 'Danmark'),
('de', 'en', 'United Kingdom'),
('de', 'es', 'España'),
('de', 'fi', 'Suomi'),
('de', 'fr', 'France'),
('de', 'gr', 'Ελλάδα'),
('de', 'hr', 'Hrvatska'),
('de', 'hu', 'Magyarország'),
('de', 'it', 'Italia'),
('de', 'jp', '日本'),
('de', 'mx', 'México'),
('de', 'nl', 'Nederland'),
('de', 'no', 'Norge'),
('de', 'pl', 'Polska'),
('de', 'pt', 'Portugal'),
('de', 'ro', 'Romania'),
('de', 'ru', 'Российская Федерация'),
('de', 'se', 'Sverige'),
('de', 'si', 'Slovenija'),
('de', 'sk', 'Slovensko'),
('de', 'tr', 'Türkiye'),
('de', 'tw', '台灣'),
('de', 'us', 'USA'),
('dk', 'ar', 'Argentina'),
('dk', 'br', 'Brasil'),
('dk', 'cz', 'Česká Republika'),
('dk', 'de', 'Deutschland'),
('dk', 'dk', 'Danmark'),
('dk', 'en', 'United Kingdom'),
('dk', 'es', 'España'),
('dk', 'fi', 'Suomi'),
('dk', 'fr', 'France'),
('dk', 'gr', 'Ελλάδα'),
('dk', 'hr', 'Hrvatska'),
('dk', 'hu', 'Magyarország'),
('dk', 'it', 'Italia'),
('dk', 'jp', '日本'),
('dk', 'mx', 'México'),
('dk', 'nl', 'Nederland'),
('dk', 'no', 'Norge'),
('dk', 'pl', 'Polska'),
('dk', 'pt', 'Portugal'),
('dk', 'ro', 'Romania'),
('dk', 'ru', 'Российская Федерация'),
('dk', 'se', 'Sverige'),
('dk', 'si', 'Slovenija'),
('dk', 'sk', 'Slovensko'),
('dk', 'tr', 'Türkiye'),
('dk', 'tw', '台灣'),
('dk', 'us', 'USA'),
('en', 'ar', 'Argentina'),
('en', 'br', 'Brasil'),
('en', 'cz', 'Česká Republika'),
('en', 'de', 'Deutschland'),
('en', 'dk', 'Danmark'),
('en', 'en', 'United Kingdom'),
('en', 'es', 'España'),
('en', 'fi', 'Suomi'),
('en', 'fr', 'France'),
('en', 'gr', 'Ελλάδα'),
('en', 'hr', 'Hrvatska'),
('en', 'hu', 'Magyarország'),
('en', 'it', 'Italia'),
('en', 'jp', '日本'),
('en', 'mx', 'México'),
('en', 'nl', 'Nederland'),
('en', 'no', 'Norge'),
('en', 'pl', 'Polska'),
('en', 'pt', 'Portugal'),
('en', 'ro', 'Romania'),
('en', 'ru', 'Российская Федерация'),
('en', 'se', 'Sverige'),
('en', 'si', 'Slovenija'),
('en', 'sk', 'Slovensko'),
('en', 'tr', 'Türkiye'),
('en', 'tw', '台灣'),
('en', 'us', 'USA'),
('es', 'ar', 'Argentina'),
('es', 'br', 'Brasil'),
('es', 'cz', 'Česká Republika'),
('es', 'de', 'Deutschland'),
('es', 'dk', 'Danmark'),
('es', 'en', 'United Kingdom'),
('es', 'es', 'España'),
('es', 'fi', 'Suomi'),
('es', 'fr', 'France'),
('es', 'gr', 'Ελλάδα'),
('es', 'hr', 'Hrvatska'),
('es', 'hu', 'Magyarország'),
('es', 'it', 'Italia'),
('es', 'jp', '日本'),
('es', 'mx', 'México'),
('es', 'nl', 'Nederland'),
('es', 'no', 'Norge'),
('es', 'pl', 'Polska'),
('es', 'pt', 'Portugal'),
('es', 'ro', 'Romania'),
('es', 'ru', 'Российская Федерация'),
('es', 'se', 'Sverige'),
('es', 'si', 'Slovenija'),
('es', 'sk', 'Slovensko'),
('es', 'tr', 'Türkiye'),
('es', 'tw', '台灣'),
('es', 'us', 'USA'),
('fi', 'ar', 'Argentina'),
('fi', 'br', 'Brasil'),
('fi', 'cz', 'Česká Republika'),
('fi', 'de', 'Deutschland'),
('fi', 'dk', 'Danmark'),
('fi', 'en', 'United Kingdom'),
('fi', 'es', 'España'),
('fi', 'fi', 'Suomi'),
('fi', 'fr', 'France'),
('fi', 'gr', 'Ελλάδα'),
('fi', 'hr', 'Hrvatska'),
('fi', 'hu', 'Magyarország'),
('fi', 'it', 'Italia'),
('fi', 'jp', '日本'),
('fi', 'mx', 'México'),
('fi', 'nl', 'Nederland'),
('fi', 'no', 'Norge'),
('fi', 'pl', 'Polska'),
('fi', 'pt', 'Portugal'),
('fi', 'ro', 'Romania'),
('fi', 'ru', 'Российская Федерация'),
('fi', 'se', 'Sverige'),
('fi', 'si', 'Slovenija'),
('fi', 'sk', 'Slovensko'),
('fi', 'tr', 'Türkiye'),
('fi', 'tw', '台灣'),
('fi', 'us', 'USA'),
('fr', 'ar', 'Argentina'),
('fr', 'br', 'Brasil'),
('fr', 'cz', 'Česká Republika'),
('fr', 'de', 'Deutschland'),
('fr', 'dk', 'Danmark'),
('fr', 'en', 'United Kingdom'),
('fr', 'es', 'España'),
('fr', 'fi', 'Suomi'),
('fr', 'fr', 'France'),
('fr', 'gr', 'Ελλάδα'),
('fr', 'hr', 'Hrvatska'),
('fr', 'hu', 'Magyarország'),
('fr', 'it', 'Italia'),
('fr', 'jp', '日本'),
('fr', 'mx', 'México'),
('fr', 'nl', 'Nederland'),
('fr', 'no', 'Norge'),
('fr', 'pl', 'Polska'),
('fr', 'pt', 'Portugal'),
('fr', 'ro', 'Romania'),
('fr', 'ru', 'Российская Федерация'),
('fr', 'se', 'Sverige'),
('fr', 'si', 'Slovenija'),
('fr', 'sk', 'Slovensko'),
('fr', 'tr', 'Türkiye'),
('fr', 'tw', '台灣'),
('fr', 'us', 'USA'),
('gr', 'ar', 'Argentina'),
('gr', 'br', 'Brasil'),
('gr', 'cz', 'Česká Republika'),
('gr', 'de', 'Deutschland'),
('gr', 'dk', 'Danmark'),
('gr', 'en', 'United Kingdom'),
('gr', 'es', 'España'),
('gr', 'fi', 'Suomi'),
('gr', 'fr', 'France'),
('gr', 'gr', 'Ελλάδα'),
('gr', 'hr', 'Hrvatska'),
('gr', 'hu', 'Magyarország'),
('gr', 'it', 'Italia'),
('gr', 'jp', '日本'),
('gr', 'mx', 'México'),
('gr', 'nl', 'Nederland'),
('gr', 'no', 'Norge'),
('gr', 'pl', 'Polska'),
('gr', 'pt', 'Portugal'),
('gr', 'ro', 'Romania'),
('gr', 'ru', 'Российская Федерация'),
('gr', 'se', 'Sverige'),
('gr', 'si', 'Slovenija'),
('gr', 'sk', 'Slovensko'),
('gr', 'tr', 'Türkiye'),
('gr', 'tw', '台灣'),
('gr', 'us', 'USA'),
('hr', 'ar', 'Argentina'),
('hr', 'br', 'Brasil'),
('hr', 'cz', 'Česká Republika'),
('hr', 'de', 'Deutschland'),
('hr', 'dk', 'Danmark'),
('hr', 'en', 'United Kingdom'),
('hr', 'es', 'España'),
('hr', 'fi', 'Suomi'),
('hr', 'fr', 'France'),
('hr', 'gr', 'Ελλάδα'),
('hr', 'hr', 'Hrvatska'),
('hr', 'hu', 'Magyarország'),
('hr', 'it', 'Italia'),
('hr', 'jp', '日本'),
('hr', 'mx', 'México'),
('hr', 'nl', 'Nederland'),
('hr', 'no', 'Norge'),
('hr', 'pl', 'Polska'),
('hr', 'pt', 'Portugal'),
('hr', 'ro', 'Romania'),
('hr', 'ru', 'Российская Федерация'),
('hr', 'se', 'Sverige'),
('hr', 'si', 'Slovenija'),
('hr', 'sk', 'Slovensko'),
('hr', 'tr', 'Türkiye'),
('hr', 'tw', '台灣'),
('hr', 'us', 'USA'),
('hu', 'ar', 'Argentina'),
('hu', 'br', 'Brasil'),
('hu', 'cz', 'Česká Republika'),
('hu', 'de', 'Deutschland'),
('hu', 'dk', 'Danmark'),
('hu', 'en', 'United Kingdom'),
('hu', 'es', 'España'),
('hu', 'fi', 'Suomi'),
('hu', 'fr', 'France'),
('hu', 'gr', 'Ελλάδα'),
('hu', 'hr', 'Hrvatska'),
('hu', 'hu', 'Magyarország'),
('hu', 'it', 'Italia'),
('hu', 'jp', '日本'),
('hu', 'mx', 'México'),
('hu', 'nl', 'Nederland'),
('hu', 'no', 'Norge'),
('hu', 'pl', 'Polska'),
('hu', 'pt', 'Portugal'),
('hu', 'ro', 'Romania'),
('hu', 'ru', 'Российская Федерация'),
('hu', 'se', 'Sverige'),
('hu', 'si', 'Slovenija'),
('hu', 'sk', 'Slovensko'),
('hu', 'tr', 'Türkiye'),
('hu', 'tw', '台灣'),
('hu', 'us', 'USA'),
('it', 'ar', 'Argentina'),
('it', 'br', 'Brasil'),
('it', 'cz', 'Česká Republika'),
('it', 'de', 'Deutschland'),
('it', 'dk', 'Danmark'),
('it', 'en', 'United Kingdom'),
('it', 'es', 'España'),
('it', 'fi', 'Suomi'),
('it', 'fr', 'France'),
('it', 'gr', 'Ελλάδα'),
('it', 'hr', 'Hrvatska'),
('it', 'hu', 'Magyarország'),
('it', 'it', 'Italia'),
('it', 'jp', '日本'),
('it', 'mx', 'México'),
('it', 'nl', 'Nederland'),
('it', 'no', 'Norge'),
('it', 'pl', 'Polska'),
('it', 'pt', 'Portugal'),
('it', 'ro', 'Romania'),
('it', 'ru', 'Российская Федерация'),
('it', 'se', 'Sverige'),
('it', 'si', 'Slovenija'),
('it', 'sk', 'Slovensko'),
('it', 'tr', 'Türkiye'),
('it', 'tw', '台灣'),
('it', 'us', 'USA'),
('jp', 'ar', 'Argentina'),
('jp', 'br', 'Brasil'),
('jp', 'cz', 'Česká Republika'),
('jp', 'de', 'Deutschland'),
('jp', 'dk', 'Danmark'),
('jp', 'en', 'United Kingdom'),
('jp', 'es', 'España'),
('jp', 'fi', 'Suomi'),
('jp', 'fr', 'France'),
('jp', 'gr', 'Ελλάδα'),
('jp', 'hr', 'Hrvatska'),
('jp', 'hu', 'Magyarország'),
('jp', 'it', 'Italia'),
('jp', 'jp', '日本'),
('jp', 'mx', 'México'),
('jp', 'nl', 'Nederland'),
('jp', 'no', 'Norge'),
('jp', 'pl', 'Polska'),
('jp', 'pt', 'Portugal'),
('jp', 'ro', 'Romania'),
('jp', 'ru', 'Российская Федерация'),
('jp', 'se', 'Sverige'),
('jp', 'si', 'Slovenija'),
('jp', 'sk', 'Slovensko'),
('jp', 'tr', 'Türkiye'),
('jp', 'tw', '台灣'),
('jp', 'us', 'USA'),
('mx', 'ar', 'Argentina'),
('mx', 'br', 'Brasil'),
('mx', 'cz', 'Česká Republika'),
('mx', 'de', 'Deutschland'),
('mx', 'dk', 'Danmark'),
('mx', 'en', 'United Kingdom'),
('mx', 'es', 'España'),
('mx', 'fi', 'Suomi'),
('mx', 'fr', 'France'),
('mx', 'gr', 'Ελλάδα'),
('mx', 'hr', 'Hrvatska'),
('mx', 'hu', 'Magyarország'),
('mx', 'it', 'Italia'),
('mx', 'jp', '日本'),
('mx', 'mx', 'México'),
('mx', 'nl', 'Nederland'),
('mx', 'no', 'Norge'),
('mx', 'pl', 'Polska'),
('mx', 'pt', 'Portugal'),
('mx', 'ro', 'Romania'),
('mx', 'ru', 'Российская Федерация'),
('mx', 'se', 'Sverige'),
('mx', 'si', 'Slovenija'),
('mx', 'sk', 'Slovensko'),
('mx', 'tr', 'Türkiye'),
('mx', 'tw', '台灣'),
('mx', 'us', 'USA'),
('nl', 'ar', 'Argentina'),
('nl', 'br', 'Brasil'),
('nl', 'cz', 'Česká Republika'),
('nl', 'de', 'Deutschland'),
('nl', 'dk', 'Danmark'),
('nl', 'en', 'United Kingdom'),
('nl', 'es', 'España'),
('nl', 'fi', 'Suomi'),
('nl', 'fr', 'France'),
('nl', 'gr', 'Ελλάδα'),
('nl', 'hr', 'Hrvatska'),
('nl', 'hu', 'Magyarország'),
('nl', 'it', 'Italia'),
('nl', 'jp', '日本'),
('nl', 'mx', 'México'),
('nl', 'nl', 'Nederland'),
('nl', 'no', 'Norge'),
('nl', 'pl', 'Polska'),
('nl', 'pt', 'Portugal'),
('nl', 'ro', 'Romania'),
('nl', 'ru', 'Российская Федерация'),
('nl', 'se', 'Sverige'),
('nl', 'si', 'Slovenija'),
('nl', 'sk', 'Slovensko'),
('nl', 'tr', 'Türkiye'),
('nl', 'tw', '台灣'),
('nl', 'us', 'USA'),
('no', 'ar', 'Argentina'),
('no', 'br', 'Brasil'),
('no', 'cz', 'Česká Republika'),
('no', 'de', 'Deutschland'),
('no', 'dk', 'Danmark'),
('no', 'en', 'United Kingdom'),
('no', 'es', 'España'),
('no', 'fi', 'Suomi'),
('no', 'fr', 'France'),
('no', 'gr', 'Ελλάδα'),
('no', 'hr', 'Hrvatska'),
('no', 'hu', 'Magyarország'),
('no', 'it', 'Italia'),
('no', 'jp', '日本'),
('no', 'mx', 'México'),
('no', 'nl', 'Nederland'),
('no', 'no', 'Norge'),
('no', 'pl', 'Polska'),
('no', 'pt', 'Portugal'),
('no', 'ro', 'Romania'),
('no', 'ru', 'Российская Федерация'),
('no', 'se', 'Sverige'),
('no', 'si', 'Slovenija'),
('no', 'sk', 'Slovensko'),
('no', 'tr', 'Türkiye'),
('no', 'tw', '台灣'),
('no', 'us', 'USA'),
('pl', 'ar', 'Argentina'),
('pl', 'br', 'Brasil'),
('pl', 'cz', 'Česká Republika'),
('pl', 'de', 'Deutschland'),
('pl', 'dk', 'Danmark'),
('pl', 'en', 'United Kingdom'),
('pl', 'es', 'España'),
('pl', 'fi', 'Suomi'),
('pl', 'fr', 'France'),
('pl', 'gr', 'Ελλάδα'),
('pl', 'hr', 'Hrvatska'),
('pl', 'hu', 'Magyarország'),
('pl', 'it', 'Italia'),
('pl', 'jp', '日本'),
('pl', 'mx', 'México'),
('pl', 'nl', 'Nederland'),
('pl', 'no', 'Norge'),
('pl', 'pl', 'Polska'),
('pl', 'pt', 'Portugal'),
('pl', 'ro', 'Romania'),
('pl', 'ru', 'Российская Федерация'),
('pl', 'se', 'Sverige'),
('pl', 'si', 'Slovenija'),
('pl', 'sk', 'Slovensko'),
('pl', 'tr', 'Türkiye'),
('pl', 'tw', '台灣'),
('pl', 'us', 'USA'),
('pt', 'ar', 'Argentina'),
('pt', 'br', 'Brasil'),
('pt', 'cz', 'Česká Republika'),
('pt', 'de', 'Deutschland'),
('pt', 'dk', 'Danmark'),
('pt', 'en', 'United Kingdom'),
('pt', 'es', 'España'),
('pt', 'fi', 'Suomi'),
('pt', 'fr', 'France'),
('pt', 'gr', 'Ελλάδα'),
('pt', 'hr', 'Hrvatska'),
('pt', 'hu', 'Magyarország'),
('pt', 'it', 'Italia'),
('pt', 'jp', '日本'),
('pt', 'mx', 'México'),
('pt', 'nl', 'Nederland'),
('pt', 'no', 'Norge'),
('pt', 'pl', 'Polska'),
('pt', 'pt', 'Portugal'),
('pt', 'ro', 'Romania'),
('pt', 'ru', 'Российская Федерация'),
('pt', 'se', 'Sverige'),
('pt', 'si', 'Slovenija'),
('pt', 'sk', 'Slovensko'),
('pt', 'tr', 'Türkiye'),
('pt', 'tw', '台灣'),
('pt', 'us', 'USA'),
('ro', 'ar', 'Argentina'),
('ro', 'br', 'Brasil'),
('ro', 'cz', 'Česká Republika'),
('ro', 'de', 'Deutschland'),
('ro', 'dk', 'Danmark'),
('ro', 'en', 'United Kingdom'),
('ro', 'es', 'España'),
('ro', 'fi', 'Suomi'),
('ro', 'fr', 'France'),
('ro', 'gr', 'Ελλάδα'),
('ro', 'hr', 'Hrvatska'),
('ro', 'hu', 'Magyarország'),
('ro', 'it', 'Italia'),
('ro', 'jp', '日本'),
('ro', 'mx', 'México'),
('ro', 'nl', 'Nederland'),
('ro', 'no', 'Norge'),
('ro', 'pl', 'Polska'),
('ro', 'pt', 'Portugal'),
('ro', 'ro', 'Romania'),
('ro', 'ru', 'Российская Федерация'),
('ro', 'se', 'Sverige'),
('ro', 'si', 'Slovenija'),
('ro', 'sk', 'Slovensko'),
('ro', 'tr', 'Türkiye'),
('ro', 'tw', '台灣'),
('ro', 'us', 'USA'),
('ru', 'ar', 'Argentina'),
('ru', 'br', 'Brasil'),
('ru', 'cz', 'Česká Republika'),
('ru', 'de', 'Deutschland'),
('ru', 'dk', 'Danmark'),
('ru', 'en', 'United Kingdom'),
('ru', 'es', 'España'),
('ru', 'fi', 'Suomi'),
('ru', 'fr', 'France'),
('ru', 'gr', 'Ελλάδα'),
('ru', 'hr', 'Hrvatska'),
('ru', 'hu', 'Magyarország'),
('ru', 'it', 'Italia'),
('ru', 'jp', '日本'),
('ru', 'mx', 'México'),
('ru', 'nl', 'Nederland'),
('ru', 'no', 'Norge'),
('ru', 'pl', 'Polska'),
('ru', 'pt', 'Portugal'),
('ru', 'ro', 'Romania'),
('ru', 'ru', 'Российская Федерация'),
('ru', 'se', 'Sverige'),
('ru', 'si', 'Slovenija'),
('ru', 'sk', 'Slovensko'),
('ru', 'tr', 'Türkiye'),
('ru', 'tw', '台灣'),
('ru', 'us', 'USA'),
('se', 'ar', 'Argentina'),
('se', 'br', 'Brasil'),
('se', 'cz', 'Česká Republika'),
('se', 'de', 'Deutschland'),
('se', 'dk', 'Danmark'),
('se', 'en', 'United Kingdom'),
('se', 'es', 'España'),
('se', 'fi', 'Suomi'),
('se', 'fr', 'France'),
('se', 'gr', 'Ελλάδα'),
('se', 'hr', 'Hrvatska'),
('se', 'hu', 'Magyarország'),
('se', 'it', 'Italia'),
('se', 'jp', '日本'),
('se', 'mx', 'México'),
('se', 'nl', 'Nederland'),
('se', 'no', 'Norge'),
('se', 'pl', 'Polska'),
('se', 'pt', 'Portugal'),
('se', 'ro', 'Romania'),
('se', 'ru', 'Российская Федерация'),
('se', 'se', 'Sverige'),
('se', 'si', 'Slovenija'),
('se', 'sk', 'Slovensko'),
('se', 'tr', 'Türkiye'),
('se', 'tw', '台灣'),
('se', 'us', 'USA'),
('si', 'ar', 'Argentina'),
('si', 'br', 'Brasil'),
('si', 'cz', 'Česká Republika'),
('si', 'de', 'Deutschland'),
('si', 'dk', 'Danmark'),
('si', 'en', 'United Kingdom'),
('si', 'es', 'España'),
('si', 'fi', 'Suomi'),
('si', 'fr', 'France'),
('si', 'gr', 'Ελλάδα'),
('si', 'hr', 'Hrvatska'),
('si', 'hu', 'Magyarország'),
('si', 'it', 'Italia'),
('si', 'jp', '日本'),
('si', 'mx', 'México'),
('si', 'nl', 'Nederland'),
('si', 'no', 'Norge'),
('si', 'pl', 'Polska'),
('si', 'pt', 'Portugal'),
('si', 'ro', 'Romania'),
('si', 'ru', 'Российская Федерация'),
('si', 'se', 'Sverige'),
('si', 'si', 'Slovenija'),
('si', 'sk', 'Slovensko'),
('si', 'tr', 'Türkiye'),
('si', 'tw', '台灣'),
('si', 'us', 'USA'),
('sk', 'ar', 'Argentina'),
('sk', 'br', 'Brasil'),
('sk', 'cz', 'Česká Republika'),
('sk', 'de', 'Deutschland'),
('sk', 'dk', 'Danmark'),
('sk', 'en', 'United Kingdom'),
('sk', 'es', 'España'),
('sk', 'fi', 'Suomi'),
('sk', 'fr', 'France'),
('sk', 'gr', 'Ελλάδα'),
('sk', 'hr', 'Hrvatska'),
('sk', 'hu', 'Magyarország'),
('sk', 'it', 'Italia'),
('sk', 'jp', '日本'),
('sk', 'mx', 'México'),
('sk', 'nl', 'Nederland'),
('sk', 'no', 'Norge'),
('sk', 'pl', 'Polska'),
('sk', 'pt', 'Portugal'),
('sk', 'ro', 'Romania'),
('sk', 'ru', 'Российская Федерация'),
('sk', 'se', 'Sverige'),
('sk', 'si', 'Slovenija'),
('sk', 'sk', 'Slovensko'),
('sk', 'tr', 'Türkiye'),
('sk', 'tw', '台灣'),
('sk', 'us', 'USA'),
('tr', 'ar', 'Argentina'),
('tr', 'br', 'Brasil'),
('tr', 'cz', 'Česká Republika'),
('tr', 'de', 'Deutschland'),
('tr', 'dk', 'Danmark'),
('tr', 'en', 'United Kingdom'),
('tr', 'es', 'España'),
('tr', 'fi', 'Suomi'),
('tr', 'fr', 'France'),
('tr', 'gr', 'Ελλάδα'),
('tr', 'hr', 'Hrvatska'),
('tr', 'hu', 'Magyarország'),
('tr', 'it', 'Italia'),
('tr', 'jp', '日本'),
('tr', 'mx', 'México'),
('tr', 'nl', 'Nederland'),
('tr', 'no', 'Norge'),
('tr', 'pl', 'Polska'),
('tr', 'pt', 'Portugal'),
('tr', 'ro', 'Romania'),
('tr', 'ru', 'Российская Федерация'),
('tr', 'se', 'Sverige'),
('tr', 'si', 'Slovenija'),
('tr', 'sk', 'Slovensko'),
('tr', 'tr', 'Türkiye'),
('tr', 'tw', '台灣'),
('tr', 'us', 'USA'),
('tw', 'ar', 'Argentina'),
('tw', 'br', 'Brasil'),
('tw', 'cz', 'Česká Republika'),
('tw', 'de', 'Deutschland'),
('tw', 'dk', 'Danmark'),
('tw', 'en', 'United Kingdom'),
('tw', 'es', 'España'),
('tw', 'fi', 'Suomi'),
('tw', 'fr', 'France'),
('tw', 'gr', 'Ελλάδα'),
('tw', 'hr', 'Hrvatska'),
('tw', 'hu', 'Magyarország'),
('tw', 'it', 'Italia'),
('tw', 'jp', '日本'),
('tw', 'mx', 'México'),
('tw', 'nl', 'Nederland'),
('tw', 'no', 'Norge'),
('tw', 'pl', 'Polska'),
('tw', 'pt', 'Portugal'),
('tw', 'ro', 'Romania'),
('tw', 'ru', 'Российская Федерация'),
('tw', 'se', 'Sverige'),
('tw', 'si', 'Slovenija'),
('tw', 'sk', 'Slovensko'),
('tw', 'tr', 'Türkiye'),
('tw', 'tw', '台灣'),
('tw', 'us', 'USA'),
('us', 'ar', 'Argentina'),
('us', 'br', 'Brasil'),
('us', 'cz', 'Česká Republika'),
('us', 'de', 'Deutschland'),
('us', 'dk', 'Danmark'),
('us', 'en', 'United Kingdom'),
('us', 'es', 'España'),
('us', 'fi', 'Suomi'),
('us', 'fr', 'France'),
('us', 'gr', 'Ελλάδα'),
('us', 'hr', 'Hrvatska'),
('us', 'hu', 'Magyarország'),
('us', 'it', 'Italia'),
('us', 'jp', '日本'),
('us', 'mx', 'México'),
('us', 'nl', 'Nederland'),
('us', 'no', 'Norge'),
('us', 'pl', 'Polska'),
('us', 'pt', 'Portugal'),
('us', 'ro', 'Romania'),
('us', 'ru', 'Российская Федерация'),
('us', 'se', 'Sverige'),
('us', 'si', 'Slovenija'),
('us', 'sk', 'Slovensko'),
('us', 'tr', 'Türkiye'),
('us', 'tw', '台灣'),
('us', 'us', 'USA');

-- --------------------------------------------------------

--
-- Table structure for table `servers`
--

DROP TABLE IF EXISTS `servers`;
CREATE TABLE IF NOT EXISTS `servers` (
  `lang` varchar(2) NOT NULL,
  `server` varchar(64) NOT NULL,
  PRIMARY KEY (`lang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Data for table `servers`
--

INSERT INTO `servers` (`lang`, `server`) VALUES
('ar', 'ar.ogame.gameforge.com'),
('br', 'br.ogame.gameforge.com'),
('cz', 'cz.ogame.gameforge.com'),
('de', 'de.ogame.gameforge.com'),
('dk', 'dk.ogame.gameforge.com'),
('en', 'en.ogame.gameforge.com'),
('es', 'es.ogame.gameforge.com'),
('fi', 'fi.ogame.gameforge.com'),
('fr', 'fr.ogame.gameforge.com'),
('gr', 'gr.ogame.gameforge.com'),
('hr', 'hr.ogame.gameforge.com'),
('hu', 'hu.ogame.gameforge.com'),
('it', 'it.ogame.gameforge.com'),
('jp', 'jp.ogame.gameforge.com'),
('mx', 'mx.ogame.gameforge.com'),
('nl', 'nl.ogame.gameforge.com'),
('no', 'no.ogame.gameforge.com'),
('pl', 'pl.ogame.gameforge.com'),
('pt', 'pt.ogame.gameforge.com'),
('ro', 'ro.ogame.gameforge.com'),
('ru', 'ru.ogame.gameforge.com'),
('se', 'se.ogame.gameforge.com'),
('si', 'si.ogame.gameforge.com'),
('sk', 'sk.ogame.gameforge.com'),
('tr', 'tr.ogame.gameforge.com'),
('tw', 'tw.ogame.gameforge.com'),
('us', 'us.ogame.gameforge.com');

-- --------------------------------------------------------

--
-- Table structure for table `universes`
--

DROP TABLE IF EXISTS `universes`;
CREATE TABLE IF NOT EXISTS `universes` (
  `lang` varchar(2) NOT NULL,
  `sid` smallint(6) NOT NULL,
  `server` varchar(64) NOT NULL,
  `name` varchar(40) NOT NULL,
  PRIMARY KEY (`lang`,`sid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Data for table `universes`
--

INSERT INTO `universes` (`lang`, `sid`, `server`, `name`) VALUES
('ar', 1, 's156-ar.ogame.gameforge.com', 'Dorado'),
('ar', 2, 's157-ar.ogame.gameforge.com', 'Europa'),
('ar', 3, 's158-ar.ogame.gameforge.com', 'Fenrir'),
('ar', 4, 's159-ar.ogame.gameforge.com', 'Galatea'),
('ar', 5, 's160-ar.ogame.gameforge.com', 'Himalia'),
('ar', 6, 's161-ar.ogame.gameforge.com', 'Indus'),
('ar', 7, 's162-ar.ogame.gameforge.com', 'Janice'),
('ar', 8, 's163-ar.ogame.gameforge.com', 'Kalyke'),
('br', 9, 's155-br.ogame.gameforge.com', 'Cosmos'),
('br', 10, 's163-br.ogame.gameforge.com', 'Kalyke'),
('br', 11, 's166-br.ogame.gameforge.com', 'Norma'),
('br', 12, 's167-br.ogame.gameforge.com', 'Octans'),
('br', 13, 's168-br.ogame.gameforge.com', 'Pasiphae'),
('br', 14, 's169-br.ogame.gameforge.com', 'Quasar'),
('br', 15, 's170-br.ogame.gameforge.com', 'Rosalind'),
('br', 16, 's171-br.ogame.gameforge.com', 'Sombrero'),
('br', 17, 's172-br.ogame.gameforge.com', 'Tucana'),
('br', 18, 's173-br.ogame.gameforge.com', 'Umbra'),
('br', 19, 's174-br.ogame.gameforge.com', 'Volans'),
('cz', 20, 's173-cz.ogame.gameforge.com', 'Umbra'),
('cz', 21, 's178-cz.ogame.gameforge.com', 'Zenith'),
('cz', 22, 's179-cz.ogame.gameforge.com', 'Atlas'),
('cz', 23, 's188-cz.ogame.gameforge.com', 'Juno'),
('cz', 24, 's189-cz.ogame.gameforge.com', 'Kerberos'),
('cz', 25, 's190-cz.ogame.gameforge.com', 'Lacerta'),
('cz', 26, 's191-cz.ogame.gameforge.com', 'Mathilde'),
('cz', 27, 's192-cz.ogame.gameforge.com', 'Narvi'),
('cz', 28, 's193-cz.ogame.gameforge.com', 'Ozone'),
('cz', 29, 's194-cz.ogame.gameforge.com', 'Perseus'),
('cz', 30, 's195-cz.ogame.gameforge.com', 'Quadrantids'),
('cz', 31, 's196-cz.ogame.gameforge.com', 'Rasalas'),
('de', 32, 's1-de.ogame.gameforge.com', 'Uni1'),
('de', 33, 's171-de.ogame.gameforge.com', 'Sombrero'),
('de', 34, 's199-de.ogame.gameforge.com', 'Undae'),
('de', 35, 's258-de.ogame.gameforge.com', 'Ceres'),
('de', 36, 's259-de.ogame.gameforge.com', 'Delphinus'),
('de', 37, 's260-de.ogame.gameforge.com', 'Eris'),
('de', 38, 's261-de.ogame.gameforge.com', 'Fafnir'),
('de', 39, 's262-de.ogame.gameforge.com', 'Grus'),
('de', 40, 's266-de.ogame.gameforge.com', 'Keid'),
('de', 41, 's267-de.ogame.gameforge.com', 'Lyra'),
('de', 42, 's268-de.ogame.gameforge.com', 'Mars'),
('de', 43, 's269-de.ogame.gameforge.com', 'Nembus'),
('de', 44, 's270-de.ogame.gameforge.com', 'Ophiuchus'),
('de', 45, 's271-de.ogame.gameforge.com', 'Pluto'),
('de', 46, 's272-de.ogame.gameforge.com', 'Quasi-Stellar'),
('de', 47, 's273-de.ogame.gameforge.com', 'Regulus'),
('de', 48, 's274-de.ogame.gameforge.com', 'Scorpius'),
('de', 49, 's275-de.ogame.gameforge.com', 'Titania'),
('de', 50, 's276-de.ogame.gameforge.com', 'Ukdah'),
('dk', 51, 's1-dk.ogame.gameforge.com', 'Univers 1'),
('dk', 52, 's142-dk.ogame.gameforge.com', 'Polaris'),
('dk', 53, 's154-dk.ogame.gameforge.com', 'Bellatrix'),
('dk', 54, 's155-dk.ogame.gameforge.com', 'Cosmos'),
('dk', 55, 's156-dk.ogame.gameforge.com', 'Dorado'),
('dk', 56, 's157-dk.ogame.gameforge.com', 'Europa'),
('en', 57, 's1-en.ogame.gameforge.com', 'Universe 1'),
('en', 58, 's122-en.ogame.gameforge.com', 'Vega'),
('en', 59, 's174-en.ogame.gameforge.com', 'Volans'),
('en', 60, 's190-en.ogame.gameforge.com', 'Lacerta'),
('en', 61, 's198-en.ogame.gameforge.com', 'Thuban'),
('en', 62, 's261-en.ogame.gameforge.com', 'Fafnir'),
('en', 63, 's262-en.ogame.gameforge.com', 'Grus'),
('en', 64, 's263-en.ogame.gameforge.com', 'Hercules'),
('en', 65, 's264-en.ogame.gameforge.com', 'Imai'),
('en', 66, 's265-en.ogame.gameforge.com', 'Jishui'),
('en', 67, 's266-en.ogame.gameforge.com', 'Keid'),
('en', 68, 's267-en.ogame.gameforge.com', 'Lyra'),
('en', 69, 's268-en.ogame.gameforge.com', 'Mars'),
('en', 70, 's269-en.ogame.gameforge.com', 'Nembus'),
('en', 71, 's270-en.ogame.gameforge.com', 'Ophiuchus'),
('en', 72, 's300-en.ogame.gameforge.com', 'Universe 300'),
('en', 73, 's301-en.ogame.gameforge.com', 'Universe 301'),
('es', 74, 's1-es.ogame.gameforge.com', 'Uni1'),
('es', 75, 's256-es.ogame.gameforge.com', 'Aries'),
('es', 76, 's257-es.ogame.gameforge.com', 'Bharani'),
('es', 77, 's258-es.ogame.gameforge.com', 'Ceres'),
('es', 78, 's261-es.ogame.gameforge.com', 'Fafnir'),
('es', 79, 's262-es.ogame.gameforge.com', 'Grus'),
('es', 80, 's263-es.ogame.gameforge.com', 'Hercules'),
('es', 81, 's264-es.ogame.gameforge.com', 'Imai'),
('es', 82, 's265-es.ogame.gameforge.com', 'Jishui'),
('es', 83, 's266-es.ogame.gameforge.com', 'Keid'),
('es', 84, 's267-es.ogame.gameforge.com', 'Lyra'),
('es', 85, 's268-es.ogame.gameforge.com', 'Mars'),
('fr', 86, 's172-fr.ogame.gameforge.com', 'Tucana'),
('fr', 87, 's198-fr.ogame.gameforge.com', 'Thuban'),
('fr', 88, 's253-fr.ogame.gameforge.com', 'Xuange'),
('fr', 89, 's258-fr.ogame.gameforge.com', 'Ceres'),
('fr', 90, 's260-fr.ogame.gameforge.com', 'Eris'),
('fr', 91, 's263-fr.ogame.gameforge.com', 'Hercules'),
('fr', 92, 's267-fr.ogame.gameforge.com', 'Lyra'),
('fr', 93, 's268-fr.ogame.gameforge.com', 'Mars'),
('fr', 94, 's269-fr.ogame.gameforge.com', 'Nembus'),
('fr', 95, 's270-fr.ogame.gameforge.com', 'Ophiuchus'),
('fr', 96, 's271-fr.ogame.gameforge.com', 'Pluto'),
('fr', 97, 's272-fr.ogame.gameforge.com', 'Quasi-Stellar'),
('fr', 98, 's273-fr.ogame.gameforge.com', 'Regulus'),
('fr', 99, 's274-fr.ogame.gameforge.com', 'Scorpius'),
('fr', 100, 's275-fr.ogame.gameforge.com', 'Titania'),
('fr', 101, 's276-fr.ogame.gameforge.com', 'Ukdah'),
('gr', 102, 's1-gr.ogame.gameforge.com', 'Î£ÏÎ¼Ï€Î±Î½ 1'),
('gr', 103, 's120-gr.ogame.gameforge.com', 'Taurus'),
('gr', 104, 's133-gr.ogame.gameforge.com', 'Ganimed'),
('gr', 105, 's137-gr.ogame.gameforge.com', 'Kallisto'),
('gr', 106, 's138-gr.ogame.gameforge.com', 'Libra'),
('gr', 107, 's142-gr.ogame.gameforge.com', 'Polaris'),
('gr', 108, 's143-gr.ogame.gameforge.com', 'Quaoar'),
('gr', 109, 's144-gr.ogame.gameforge.com', 'Rhea'),
('gr', 110, 's145-gr.ogame.gameforge.com', 'Spica'),
('gr', 111, 's146-gr.ogame.gameforge.com', 'Tarazed'),
('gr', 112, 's147-gr.ogame.gameforge.com', 'Uriel'),
('gr', 113, 's148-gr.ogame.gameforge.com', 'Virgo'),
('hr', 114, 's125-hr.ogame.gameforge.com', 'Yakini'),
('hr', 115, 's127-hr.ogame.gameforge.com', 'Antares'),
('hr', 116, 's137-hr.ogame.gameforge.com', 'Kallisto'),
('hr', 117, 's138-hr.ogame.gameforge.com', 'Libra'),
('hr', 118, 's139-hr.ogame.gameforge.com', 'Merkur'),
('hr', 119, 's140-hr.ogame.gameforge.com', 'Nusakan'),
('hr', 120, 's141-hr.ogame.gameforge.com', 'Oberon'),
('hr', 121, 's142-hr.ogame.gameforge.com', 'Polaris'),
('hr', 122, 's143-hr.ogame.gameforge.com', 'Quaoar'),
('hu', 123, 's160-hu.ogame.gameforge.com', 'Himalia'),
('hu', 124, 's163-hu.ogame.gameforge.com', 'Kalyke'),
('hu', 125, 's164-hu.ogame.gameforge.com', 'Leda'),
('hu', 126, 's165-hu.ogame.gameforge.com', 'Mensa'),
('hu', 127, 's168-hu.ogame.gameforge.com', 'Pasiphae'),
('hu', 128, 's169-hu.ogame.gameforge.com', 'Quasar'),
('hu', 129, 's170-hu.ogame.gameforge.com', 'Rosalind'),
('hu', 130, 's171-hu.ogame.gameforge.com', 'Sombrero'),
('hu', 131, 's172-hu.ogame.gameforge.com', 'Tucana'),
('hu', 132, 's173-hu.ogame.gameforge.com', 'Umbra'),
('hu', 133, 's174-hu.ogame.gameforge.com', 'Volans'),
('hu', 134, 's175-hu.ogame.gameforge.com', 'Weywot'),
('hu', 135, 's176-hu.ogame.gameforge.com', 'Xanthippe'),
('hu', 136, 's177-hu.ogame.gameforge.com', 'Ymir'),
('it', 137, 's195-it.ogame.gameforge.com', 'Quadrantids'),
('it', 138, 's254-it.ogame.gameforge.com', 'Yin'),
('it', 139, 's264-it.ogame.gameforge.com', 'Imai'),
('it', 140, 's265-it.ogame.gameforge.com', 'Jishui'),
('it', 141, 's266-it.ogame.gameforge.com', 'Keid'),
('it', 142, 's267-it.ogame.gameforge.com', 'Lyra'),
('it', 143, 's268-it.ogame.gameforge.com', 'Mars'),
('it', 144, 's269-it.ogame.gameforge.com', 'Nembus'),
('it', 145, 's270-it.ogame.gameforge.com', 'Ophiuchus'),
('it', 146, 's271-it.ogame.gameforge.com', 'Pluto'),
('jp', 147, 's101-jp.ogame.gameforge.com', 'Andromeda'),
('jp', 148, 's117-jp.ogame.gameforge.com', 'Quantum'),
('mx', 149, 's143-mx.ogame.gameforge.com', 'Quaoar'),
('mx', 150, 's147-mx.ogame.gameforge.com', 'Uriel'),
('mx', 151, 's148-mx.ogame.gameforge.com', 'Virgo'),
('mx', 152, 's149-mx.ogame.gameforge.com', 'Wezn'),
('mx', 153, 's150-mx.ogame.gameforge.com', 'Xanthus'),
('mx', 154, 's151-mx.ogame.gameforge.com', 'Yildun'),
('mx', 155, 's152-mx.ogame.gameforge.com', 'Zibal'),
('nl', 156, 's153-nl.ogame.gameforge.com', 'Aquarius'),
('nl', 157, 's154-nl.ogame.gameforge.com', 'Bellatrix'),
('nl', 158, 's155-nl.ogame.gameforge.com', 'Cosmos'),
('nl', 159, 's168-nl.ogame.gameforge.com', 'Pasiphae'),
('nl', 160, 's169-nl.ogame.gameforge.com', 'Quasar'),
('nl', 161, 's170-nl.ogame.gameforge.com', 'Rosalind'),
('nl', 162, 's171-nl.ogame.gameforge.com', 'Sombrero'),
('nl', 163, 's172-nl.ogame.gameforge.com', 'Tucana'),
('nl', 164, 's173-nl.ogame.gameforge.com', 'Umbra'),
('nl', 165, 's174-nl.ogame.gameforge.com', 'Volans'),
('nl', 166, 's175-nl.ogame.gameforge.com', 'Weywot'),
('nl', 167, 's176-nl.ogame.gameforge.com', 'Xanthippe'),
('nl', 168, 's177-nl.ogame.gameforge.com', 'Ymir'),
('pl', 169, 's163-pl.ogame.gameforge.com', 'Kalyke'),
('pl', 170, 's170-pl.ogame.gameforge.com', 'Rosalind'),
('pl', 171, 's189-pl.ogame.gameforge.com', 'Kerberos'),
('pl', 172, 's199-pl.ogame.gameforge.com', 'Undae'),
('pl', 173, 's251-pl.ogame.gameforge.com', 'Vela'),
('pl', 174, 's259-pl.ogame.gameforge.com', 'Delphinus'),
('pl', 175, 's261-pl.ogame.gameforge.com', 'Fafnir'),
('pl', 176, 's262-pl.ogame.gameforge.com', 'Grus'),
('pl', 177, 's263-pl.ogame.gameforge.com', 'Hercules'),
('pl', 178, 's264-pl.ogame.gameforge.com', 'Imai'),
('pl', 179, 's265-pl.ogame.gameforge.com', 'Jishui'),
('pl', 180, 's266-pl.ogame.gameforge.com', 'Keid'),
('pl', 181, 's267-pl.ogame.gameforge.com', 'Lyra'),
('pl', 182, 's268-pl.ogame.gameforge.com', 'Mars'),
('pl', 183, 's269-pl.ogame.gameforge.com', 'Nembus'),
('pl', 184, 's68-pl.ogame.gameforge.com', 'Universum 68'),
('pt', 185, 's160-pt.ogame.gameforge.com', 'Himalia'),
('pt', 186, 's163-pt.ogame.gameforge.com', 'Kalyke'),
('pt', 187, 's164-pt.ogame.gameforge.com', 'Leda'),
('pt', 188, 's166-pt.ogame.gameforge.com', 'Norma'),
('pt', 189, 's167-pt.ogame.gameforge.com', 'Octans'),
('pt', 190, 's168-pt.ogame.gameforge.com', 'Pasiphae'),
('pt', 191, 's169-pt.ogame.gameforge.com', 'Quasar'),
('pt', 192, 's170-pt.ogame.gameforge.com', 'Rosalind'),
('pt', 193, 's171-pt.ogame.gameforge.com', 'Sombrero'),
('pt', 194, 's172-pt.ogame.gameforge.com', 'Tucana'),
('pt', 195, 's173-pt.ogame.gameforge.com', 'Umbra'),
('pt', 196, 's174-pt.ogame.gameforge.com', 'Volans'),
('pt', 197, 's175-pt.ogame.gameforge.com', 'Weywot'),
('ro', 198, 's124-ro.ogame.gameforge.com', 'Xalynth'),
('ro', 199, 's147-ro.ogame.gameforge.com', 'Uriel'),
('ro', 200, 's152-ro.ogame.gameforge.com', 'Zibal'),
('ro', 201, 's153-ro.ogame.gameforge.com', 'Aquarius'),
('ro', 202, 's154-ro.ogame.gameforge.com', 'Bellatrix'),
('ro', 203, 's155-ro.ogame.gameforge.com', 'Cosmos'),
('ro', 204, 's156-ro.ogame.gameforge.com', 'Dorado'),
('ro', 205, 's157-ro.ogame.gameforge.com', 'Europa'),
('ro', 206, 's158-ro.ogame.gameforge.com', 'Fenrir'),
('ro', 207, 's159-ro.ogame.gameforge.com', 'Galatea'),
('ro', 208, 's160-ro.ogame.gameforge.com', 'Himalia'),
('ro', 209, 's161-ro.ogame.gameforge.com', 'Indus'),
('ro', 210, 's162-ro.ogame.gameforge.com', 'Janice'),
('ro', 211, 's163-ro.ogame.gameforge.com', 'Kalyke'),
('ro', 212, 's164-ro.ogame.gameforge.com', 'Leda'),
('ru', 213, 's1-ru.ogame.gameforge.com', 'Ð’ÑÐµÐ»ÐµÐ½Ð½Ð°Ñ 1'),
('ru', 214, 's103-ru.ogame.gameforge.com', 'Capella'),
('ru', 215, 's178-ru.ogame.gameforge.com', 'Zenith'),
('ru', 216, 's182-ru.ogame.gameforge.com', 'Dione'),
('ru', 217, 's188-ru.ogame.gameforge.com', 'Juno'),
('ru', 218, 's193-ru.ogame.gameforge.com', 'Ozone'),
('ru', 219, 's199-ru.ogame.gameforge.com', 'Undae'),
('ru', 220, 's254-ru.ogame.gameforge.com', 'Yin'),
('ru', 221, 's255-ru.ogame.gameforge.com', 'Zodiac'),
('ru', 222, 's256-ru.ogame.gameforge.com', 'Aries'),
('ru', 223, 's257-ru.ogame.gameforge.com', 'Bharani'),
('ru', 224, 's258-ru.ogame.gameforge.com', 'Ceres'),
('ru', 225, 's259-ru.ogame.gameforge.com', 'Delphinus'),
('ru', 226, 's260-ru.ogame.gameforge.com', 'Eris'),
('ru', 227, 's261-ru.ogame.gameforge.com', 'Fafnir'),
('ru', 228, 's262-ru.ogame.gameforge.com', 'Grus'),
('si', 229, 's101-si.ogame.gameforge.com', 'Andromeda'),
('si', 230, 's106-si.ogame.gameforge.com', 'Fornax'),
('si', 231, 's112-si.ogame.gameforge.com', 'Leo'),
('si', 232, 's117-si.ogame.gameforge.com', 'Quantum'),
('si', 233, 's118-si.ogame.gameforge.com', 'Rigel'),
('sk', 234, 's108-sk.ogame.gameforge.com', 'Hydra'),
('sk', 235, 's115-sk.ogame.gameforge.com', 'Orion'),
('sk', 236, 's126-sk.ogame.gameforge.com', 'Zagadra'),
('sk', 237, 's130-sk.ogame.gameforge.com', 'Deimos'),
('sk', 238, 's131-sk.ogame.gameforge.com', 'Eridanus'),
('sk', 239, 's132-sk.ogame.gameforge.com', 'Fidis'),
('sk', 240, 's133-sk.ogame.gameforge.com', 'Ganimed'),
('tr', 241, 's1-tr.ogame.gameforge.com', 'Evr1'),
('tr', 242, 's190-tr.ogame.gameforge.com', 'Lacerta'),
('tr', 243, 's251-tr.ogame.gameforge.com', 'Vela'),
('tr', 244, 's252-tr.ogame.gameforge.com', 'Wurren'),
('tr', 245, 's259-tr.ogame.gameforge.com', 'Delphinus'),
('tr', 246, 's260-tr.ogame.gameforge.com', 'Eris'),
('tr', 247, 's261-tr.ogame.gameforge.com', 'Fafnir'),
('tr', 248, 's262-tr.ogame.gameforge.com', 'Grus'),
('tr', 249, 's263-tr.ogame.gameforge.com', 'Hercules'),
('tr', 250, 's264-tr.ogame.gameforge.com', 'Imai'),
('tr', 251, 's265-tr.ogame.gameforge.com', 'Jishui'),
('tw', 252, 's139-tw.ogame.gameforge.com', 'Merkur'),
('tw', 253, 's141-tw.ogame.gameforge.com', 'Oberon'),
('tw', 254, 's155-tw.ogame.gameforge.com', 'Cosmos'),
('tw', 255, 's159-tw.ogame.gameforge.com', 'Galatea'),
('tw', 256, 's162-tw.ogame.gameforge.com', 'Janice'),
('tw', 257, 's163-tw.ogame.gameforge.com', 'Kalyke'),
('tw', 258, 's164-tw.ogame.gameforge.com', 'Leda'),
('tw', 259, 's165-tw.ogame.gameforge.com', 'Mensa'),
('tw', 260, 's166-tw.ogame.gameforge.com', 'Norma'),
('tw', 261, 's167-tw.ogame.gameforge.com', 'Octans'),
('tw', 262, 's168-tw.ogame.gameforge.com', 'Pasiphae'),
('tw', 263, 's169-tw.ogame.gameforge.com', 'Quasar'),
('tw', 264, 's170-tw.ogame.gameforge.com', 'Rosalind'),
('us', 265, 's160-us.ogame.gameforge.com', 'Himalia'),
('us', 266, 's174-us.ogame.gameforge.com', 'Volans'),
('us', 267, 's178-us.ogame.gameforge.com', 'Zenith'),
('us', 268, 's185-us.ogame.gameforge.com', 'Gaspra'),
('us', 269, 's187-us.ogame.gameforge.com', 'Isonoe'),
('us', 270, 's192-us.ogame.gameforge.com', 'Narvi'),
('us', 271, 's195-us.ogame.gameforge.com', 'Quadrantids'),
('us', 272, 's197-us.ogame.gameforge.com', 'Saros'),
('us', 273, 's198-us.ogame.gameforge.com', 'Thuban'),
('us', 274, 's199-us.ogame.gameforge.com', 'Undae'),
('us', 275, 's251-us.ogame.gameforge.com', 'Vela'),
('us', 276, 's252-us.ogame.gameforge.com', 'Wurren'),
('us', 277, 's253-us.ogame.gameforge.com', 'Xuange'),
('us', 278, 's254-us.ogame.gameforge.com', 'Yin'),
('us', 279, 's255-us.ogame.gameforge.com', 'Zodiac'),
('us', 280, 's256-us.ogame.gameforge.com', 'Aries'),
('us', 281, 's257-us.ogame.gameforge.com', 'Bharani'),
('us', 282, 's258-us.ogame.gameforge.com', 'Ceres');
COMMIT;

--
-- Table structure for table `population_data`
--
CREATE TABLE population_data (
    country VARCHAR(2) NOT NULL,
    universe SMALLINT(6) NOT NULL,
    timestamp BIGINT UNSIGNED NOT NULL,
    population JSON NOT NULL,
    PRIMARY KEY (country, universe)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
