#!/usr/bin/env node

/**
 * Copies Bootstrap and Bootstrap Icons out of node_modules into www/vendor/.
 *
 * The site serves them itself rather than from a CDN: a third-party origin costs
 * every first visit its own DNS lookup and TLS handshake before the render-blocking
 * CSS can arrive, and the host already speaks HTTP/2. The deploy has no build step
 * (a push to main goes live as checked out), so the copies are committed.
 *
 * The versions are pinned in package.json. To upgrade, bump them there (Dependabot
 * opens the PR), run `make vendor` and commit what it writes. `make check` runs
 * this script with --check, so a version bump without a fresh copy fails CI.
 *
 * Run: node scripts/vendor-assets.js [--check]
 *   --check  verify www/vendor matches node_modules, exit non-zero if it does not.
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const MODULES = path.join(ROOT, 'node_modules');
const VENDOR = path.join(ROOT, 'www', 'vendor');

// [source under node_modules, target under www/vendor]
const FILES = [
  ['bootstrap/dist/css/bootstrap.min.css', 'bootstrap/bootstrap.min.css'],
  ['bootstrap/dist/css/bootstrap.min.css.map', 'bootstrap/bootstrap.min.css.map'],
  ['bootstrap/dist/js/bootstrap.bundle.min.js', 'bootstrap/bootstrap.bundle.min.js'],
  ['bootstrap/dist/js/bootstrap.bundle.min.js.map', 'bootstrap/bootstrap.bundle.min.js.map'],
  // The stylesheet finds the fonts at ./fonts/, so they keep that layout.
  ['bootstrap-icons/font/bootstrap-icons.min.css', 'bootstrap-icons/bootstrap-icons.min.css'],
  ['bootstrap-icons/font/fonts/bootstrap-icons.woff2', 'bootstrap-icons/fonts/bootstrap-icons.woff2'],
  ['bootstrap-icons/font/fonts/bootstrap-icons.woff', 'bootstrap-icons/fonts/bootstrap-icons.woff'],
];

const INC = 'vendor.inc.php';

/** @param {string} pkg */
function versionOf(pkg) {
  return JSON.parse(fs.readFileSync(path.join(MODULES, pkg, 'package.json'), 'utf8')).version;
}

/**
 * The PHP the page head reads. The icon stylesheet requests its font as
 * `bootstrap-icons.woff2?<hash>`, and a preload only counts when its URL matches
 * that request exactly, so the hash has to come from the stylesheet itself.
 * @returns {string}
 */
function incContent() {
  const css = fs.readFileSync(path.join(MODULES, 'bootstrap-icons/font/bootstrap-icons.min.css'), 'utf8');
  const match = /bootstrap-icons\.woff2\?([0-9a-f]+)/.exec(css);
  if (!match) {
    throw new Error('bootstrap-icons.min.css no longer names its woff2 font as expected');
  }
  return [
    '<?php',
    '// Generated by scripts/vendor-assets.js from node_modules - do not edit;',
    '// run `make vendor` after changing the versions in package.json.',
    `// bootstrap ${versionOf('bootstrap')}, bootstrap-icons ${versionOf('bootstrap-icons')}`,
    `const VENDOR_ICONS_FONT_HASH = '${match[1]}';`,
    '',
  ].join('\n');
}

/** @returns {Array<[string, Buffer]>} target path and the bytes it should hold */
function expected() {
  const out = FILES.map(([from, to]) => /** @type {[string, Buffer]} */ (
    [to, fs.readFileSync(path.join(MODULES, from))]
  ));
  out.push([INC, Buffer.from(incContent(), 'utf8')]);
  return out;
}

function main() {
  const check = process.argv.includes('--check');
  const stale = [];
  for (const [rel, bytes] of expected()) {
    const target = path.join(VENDOR, rel);
    const current = fs.existsSync(target) ? fs.readFileSync(target) : null;
    if (current?.equals(bytes)) continue;
    if (check) {
      stale.push(rel);
    } else {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, bytes);
      console.log(`wrote www/vendor/${rel}`);
    }
  }
  if (stale.length > 0) {
    console.error('www/vendor is out of date with node_modules - run `make vendor` and commit:');
    for (const rel of stale) console.error(`  www/vendor/${rel}`);
    process.exit(1);
  }
  if (check) console.log(`www/vendor matches bootstrap ${versionOf('bootstrap')}, bootstrap-icons ${versionOf('bootstrap-icons')}.`);
}

main();
